name: Deploy to staging

on:
  pull_request:

jobs:
  test:
    uses: ./.github/workflows/test.yml

  deploy-staging:
    name: Deploy to staging subaccount
    permissions:
      pull-requests: write
    needs: [test]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_TOKEN }}

    - name: Install near CLI
      run: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/near/near-cli-rs/releases/download/v0.7.0/near-cli-rs-installer.sh | sh

    - name: Create staging account
      if: github.event.action == 'opened' || github.event.action == 'reopened'
      run: |
        near account create-account fund-myself "${{ vars.NEAR_CONTRACT_STAGING_ACCOUNT_ID }}" '10 NEAR' \
          sign-as "${{ vars.NEAR_CONTRACT_STAGING_ACCOUNT_ID }}" \
          network-config "${{ vars.NEAR_CONTRACT_STAGING_NETWORK }}" \
          send

    - name: Install cargo-near CLI
      run: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/near/cargo-near/releases/download/cargo-near-v0.4.1/cargo-near-installer.sh | sh

    - name: Deploy to staging
      run: |
        cargo near deploy "${{ vars.NEAR_CONTRACT_STAGING_ACCOUNT_ID }}" \
          without-init-call \
          network-config "${{ vars.NEAR_CONTRACT_STAGING_NETWORK }}" \
          sign-with-plaintext-private-key \
          --signer-private-key "${{ secrets.NEAR_CONTRACT_STAGING_ACCOUNT_PRIVATE_KEY }}" \
          send

    - name: Comment on pull request
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        gh pr comment "${{ github.event.number }}" --body "Staging contract is deployed to \["'\`'"${{ vars.NEAR_CONTRACT_STAGING_ACCOUNT_ID }}"'\`'" account\](https://explorer.${{ vars.NEAR_CONTRACT_STAGING_NETWORK }}.near.org/accounts/${{ vars.NEAR_CONTRACT_STAGING_ACCOUNT_ID }})"